server {
    listen 443 ssl;
    server_name api.local;

    ssl_certificate     /etc/nginx/certs/cert.pem;
    ssl_certificate_key /etc/nginx/certs/key.pem;

    ssl_protocols TLSv1.2 TLSv1.3;

    location / {
        default_type application/json;
        return 200 '{"service": "backend-api", "tls": true, "ca": "shared-kalypso"}';
    }
}
